name: "Request review of a FPWD"
description: Use this if you are approaching or have just passed FPWD.
title: Document_name    2020-mm-dd
labels: [ "REVIEW REQUESTED", FPWD, pending ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        We have conducted a self-review of our spec:
        some text can go here
        ....
  - type: input
    id: spec-name
    attributes:
      label: Name of specification
      description: Copy and paste title of your specification
      placeholder: Name of specification
    validations:
      required: true
  - type: input
    id: spec-url
    attributes:
      label: URL of specification
      placeholder: https://www.w3.org/TR/...
    validations:
      required: true
  - type: input
    id: repo-issue
    attributes:
      label: URL for the issue
      placeholder: https://github.com/w3c/..../issues
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Do you need a reply by a particular date?
      description: If any date, type here
  - type: textarea
    attributes:
      label: Other comments
