name: "Request a review of a FPWD"
description: Use this if you are approaching or have just passed FPWD.
title: Document_name 2020-mm-dd
labels: [ FPWD, "REVIEW REQUESTED", pending ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        This is a test.
  - type: input
    id: spec-name
    attributes:
      label: Name of your specification
      description: Copy and paste title of your specification
      placeholder: Name of specification
    validations:
      required: true
  - type: input
    id: spec-url
    attributes:
      label: URL of your specification
      placeholder: https://www.w3.org/TR/...
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Do you need a reply by a particular date?
      description: If so, add the date here
  - type: input
    id: self
    attributes:
      label: Please point to the results of your own self-review (see https://w3c.github.io/i18n-drafts/techniques/shortchecklist).
      description: If so, add the date here
   - type: input
    id: filing
    attributes:
      label: Where and how should the i18n WG raise issues? (We prefer to use the issue list in your document's repo.)
      placeholder: Link to the location
    validations:
      required: true
   - type: input
    id: self
    attributes:
      label: Pointer to any explainer for the spec.
       placeholder: Add a URL
 - type: textarea
    attributes:
      label: Other comments

